channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - ipython
  - r-base
  - r-tidyverse
  - r-tidyr
  - r-repr
  - r-dplyr 
  - r-devtools
  - r-ggplot2
  - r-data.table
  - r-xml2
  - r-rjson
  - r-reticulate
  - pip
  - matplotlib
  - numpy
  - scipy
  - pandas
  - requests 
  - scikit-learn
  - seaborn
  - jupyter_contrib_nbextensions
  - ipywidgets
  - gdal
  - pip:
    - -r file:requirements.txt
