dependencies:
  - ipython
  - matplotlib
  - numpy
  - scipy
  - pandas
  - requests 
  - scikit-learn
  - seaborn
  - jupyter_contrib_nbextensions
  - ipywidgets
  - pip:
    - eurostatapiclient
    - jsonstat.py
    - pandaSDMX
    - dbnomics
    - simplejson
    - geojson
    - geopandas
    - shapely
    - -r file:requirements.txt
