dependencies:
  - ipython
  - matplotlib
  - numpy
  - scipy
  - pandas
  - requests 
  - scikit-learn
  - seaborn
  - jupyter_contrib_nbextensions
  - ipywidgets
  - gdal
  - pip:
    - -r file:requirements.txt
