dependencies:
  - ipython
  - pip
  - matplotlib
  - numpy
  - scipy
  - pandas
  - requests 
  - scikit-learn
  - seaborn
  - jupyter_contrib_nbextensions
  - ipywidgets
  - ipyvega
  - traitlets
  - altair 
  - vega_datasets
  - gdal
  - pip:
    - -r file:requirements.txt
