channels:
  - conda-forge
  - r
  - defaults
  - conda-forge/label/broken
dependencies:
  - ipython
  - r-essentials
  - r-rjava
  - pip
  - matplotlib
  - numpy
  - scipy
  - pandas
  - requests 
  - scikit-learn
  - seaborn
  - jupyter_contrib_nbextensions
  - ipywidgets
  - gdal
  - pip:
    - -r file:requirements.txt
